@startuml i9lyfe_api_arch
!include <C4/C4_Component>

' !includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

title i9lyfe API Server

Container(api, "i9lyfe API Server", "Go")

System_Ext(emailSystem, "Email System", "Google SMTP")
System_Ext(cloudStorageSystem, "Cloud Storage System", "Google Cloud Storage")

ContainerDb(database, "Database", "PostgreSQL")
ContainerDb(inmemorydb, "In-memory Database", "Redis Key-Value Store")
ContainerQueue(eventQueue, "Event Queue/Stream", "Redis Streams")
ContainerDb(pubsubMS, "Pub/Sub Messaging System", "Redis Pub/Sub")

Component(cloudStorageService, "Cloud Storage Service", "GCS Go client library", "Consists GCS bucket interaction and object cloud name to URL conversion routines")
Rel(cloudStorageService, cloudStorageSystem, "Uses")

Component(cache, "Cache", "go-redis", "Cache management routines: store, get, update, and delete")
Rel(cache, inmemorydb, "Reads/Writes")
Rel(cache, cloudStorageService, "Calls")

Component(securityServices, "Security Services", "Go, golang-jwt, bcrypt", "Consists security-related logic for: JWT signing/verification, Digit token generation with expiration etc.")
Component(mailService, "Mail Service", "Go, gomail.v2, crypto/tls", "Consists routine for sending email")
Component(eventStreamService, "Event Stream Service", "Go, go-redis (XAdd)", "Consists routines for queueing application events")
Rel(mailService, emailSystem, "Uses")
Rel(eventStreamService, eventQueue, "Add event")

Component(realtimeService, "Realtime Service", "Go, sync, go-redis (Publish, Subscribe, [LPOP, RPUSH]), websocket", "Consists routines for managing active user sockets, subscribing users to pub/sub messaging channels, publishing messages to channels, sending server event messages; queueing (RPUSH) undelivered messages in Redis when user socket is offline; dequeueing (LPOP) undelivered messages from Redis when user socket comes online")
Rel(realtimeService, pubsubMS, "Calls (Publish/Subscribe)")
Rel(realtimeService, inmemorydb, "Reads/Writes (LPOP, RPUSH)")

Component(userControllers, "User Controllers", "gofiber", "Consists handlers for user management requests, and user-owned resource fetching requests")
Component(userService, "User Service", "Go", "Consists user management routines, user-owned resource fetching routines, and user presence change routines")
Component(userModel, "User Model", "SQL, pgx, go-redis", "User management DB and cache query routines; User-owned resource DB and cache query routines")
Rel(userControllers, userService, "Call")
Rel(userService, userModel, "Calls")
Rel(userControllers, cloudStorageService, "Call")
Rel(userService, cloudStorageService, "Calls")
Rel(userModel, database, "Reads/Writes")
Rel(userModel, cache, "Calls")
Rel(userService, realtimeService, "Calls")
Rel(userService, eventStreamService, "Calls")

Component(signupControllers, "Signup Controllers", "gofiber", "Handles signup request steps, signup session management via cookie, stores user auth token in response cookie")
Component(signupService, "Signup Service", "Go", "Performs username or email existence checks; Performs email verification; Stores new user; Generates user auth token")
Rel(signupControllers, signupService, "Call")
Rel(signupService, securityServices, "Calls")
Rel(signupService, cloudStorageService, "Calls")
Rel(signupService, mailService, "Calls")
Rel(signupService, eventStreamService, "Calls")
Rel(signupService, userService, "Calls")

Component(signinControllers, "Signin Controllers", "gofiber", "Handles signin request, stores user auth token in response cookie")
Component(signinService, "Signin Service", "Go", "Performs username or email existence; Generates user auth token")
Rel(signinControllers, signinService, "Call")
Rel(signinService, securityServices, "Calls")
Rel(signinService, cloudStorageService, "Calls")
Rel(signinService, userService, "Calls")

Component(passwordResetControllers, "Password Reset Controllers", "gofiber", "Handles password reset request steps, password reset session management via cookie")
Component(passwordResetService, "Password Reset Service", "Go", "Confirms password reset request; Changes user password")
Rel(passwordResetControllers, passwordResetService, "Call")
Rel(passwordResetService, securityServices, "Calls")
Rel(passwordResetService, mailService, "Calls")
Rel(passwordResetService, userService, "Calls")

Component(postCommentControllers, "Post & Comment Controllers", "gofiber", "Handles all post and comment management and interaction requests")
Component(postCommentService, "Post & Comment Service", "Go", "Consists Post and comment management and interaction business logic routines")
Component(postModel, "Post Model", "SQL, pgx, go-redis", "Consitts Post management and interaction DB and cache query routines")
Component(commentModel, "Comment Model", "SQL, pgx, go-redis", "Comment management and interaction DB and cache query routines")
Rel(postCommentControllers, postCommentService, "Call")
Rel(postCommentService, postModel, "Calls")
Rel(postCommentControllers, cloudStorageService, "Call")
Rel(postCommentService, cloudStorageService, "Calls")
Rel(postCommentService, commentModel, "Calls")
Rel(postCommentService, eventStreamService, "Calls")
Rel(postModel, cache, "Calls")
Rel(postModel, database, "Reads/Writes")
Rel(commentModel, cache, "Calls")
Rel(commentModel, database, "Reads/Writes")

Component(chatControllers, "Chat Controllers", "gofiber", "Consists HTTP request handlers and Websocket message handlers for all chat related requests")
Component(chatService, "Chat Service", "Go", "Chat and messaging business logic routines")
Component(chatModel, "Chat Model", "SQL, pgx, go-redis", "Chat and messaging DB and cache query routines")
Rel(chatControllers, chatService, "Call")
Rel(chatService, chatModel, "Calls")
Rel(chatControllers, cloudStorageService, "Call")
Rel(chatService, cloudStorageService, "Calls")
Rel(chatService, eventStreamService, "Calls")
Rel(chatService, realtimeService, "Calls")
Rel(chatModel, cache, "Calls")
Rel(chatModel, database, "Reads/Writes")

Component(realtimeController, "Realtime Controller", "gofiber, websocket", "Handles Websocket HTTP Upgrade; Acquires and manages user connection stream (socket); Waits on and reads messages from user connection stream (socket)")
Rel(realtimeController, chatControllers, "Calls")
Rel(realtimeController, userService, "Calls")
Rel(realtimeController, realtimeService, "Calls")

Component(backgroundWorkers, "Background Workers", "Go, go-redis", "Consist routines that read target streams (dequeue events) and run background tasks")
Rel(backgroundWorkers, eventQueue, "Read/Dequeue")
Rel(backgroundWorkers, database, "Read/Write")
Rel(backgroundWorkers, cache, "Call")
Rel(backgroundWorkers, realtimeService, "Call")

@enduml
