// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "i9ine",
            "email": "oluwarinolasam@gmail.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/app/private/me": {
            "get": {
                "description": "Get info on the user currently in session",
                "produces": [
                    "application/vnd.msgpack"
                ],
                "tags": [
                    "app/private"
                ],
                "summary": "Get session user",
                "parameters": [
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "csv",
                        "description": "User session request cookie",
                        "name": "Cookie",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User info",
                        "schema": {
                            "$ref": "#/definitions/UITypes.ClientUser"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/appErrors.HTTPError"
                        }
                    }
                }
            }
        },
        "/app/private/me/change_profile_picture": {
            "put": {
                "description": "Change user profile picture",
                "produces": [
                    "application/vnd.msgpack"
                ],
                "tags": [
                    "app/private"
                ],
                "summary": "Change user profile picture",
                "parameters": [
                    {
                        "description": "Profile picture data",
                        "name": "picture_data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "integer"
                            }
                        }
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "csv",
                        "description": "User session request cookie",
                        "name": "Cookie",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Done",
                        "schema": {
                            "type": "boolean"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/appErrors.HTTPError"
                        }
                    }
                }
            }
        },
        "/app/private/me/edit_profile": {
            "put": {
                "description": "Edit user profile",
                "produces": [
                    "application/vnd.msgpack"
                ],
                "tags": [
                    "app/private"
                ],
                "summary": "Edit user profile",
                "parameters": [
                    {
                        "description": "User's Name field",
                        "name": "name",
                        "in": "body",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "User's Birthday field in milliseconds since Unix Epoch",
                        "name": "birthday",
                        "in": "body",
                        "schema": {
                            "type": "integer"
                        }
                    },
                    {
                        "description": "User's Bio field",
                        "name": "bio",
                        "in": "body",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "csv",
                        "description": "User session request cookie",
                        "name": "Cookie",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Done",
                        "schema": {
                            "type": "boolean"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/appErrors.HTTPError"
                        }
                    }
                }
            }
        },
        "/app/private/me/signout": {
            "get": {
                "description": "Signout the user currently in session",
                "produces": [
                    "application/vnd.msgpack"
                ],
                "tags": [
                    "app/private"
                ],
                "summary": "Signout user",
                "parameters": [
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "csv",
                        "description": "User session request cookie",
                        "name": "Cookie",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Bye message",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/appErrors.HTTPError"
                        }
                    }
                }
            }
        },
        "/app/private/users/:username/follow": {
            "post": {
                "description": "Follow user",
                "produces": [
                    "application/vnd.msgpack"
                ],
                "tags": [
                    "app/private"
                ],
                "summary": "Follow user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User to follow",
                        "name": "username",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "csv",
                        "description": "User session request cookie",
                        "name": "Cookie",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Done",
                        "schema": {
                            "type": "boolean"
                        }
                    },
                    "400": {
                        "description": "Validation error | User trying to follow self",
                        "schema": {
                            "$ref": "#/definitions/appErrors.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/appErrors.HTTPError"
                        }
                    }
                }
            }
        },
        "/app/private/users/:username/unfollow": {
            "delete": {
                "description": "Unfollow user",
                "produces": [
                    "application/vnd.msgpack"
                ],
                "tags": [
                    "app/private"
                ],
                "summary": "Unfollow user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User to unfollow",
                        "name": "username",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "csv",
                        "description": "User session request cookie",
                        "name": "Cookie",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Done",
                        "schema": {
                            "type": "boolean"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/appErrors.HTTPError"
                        }
                    }
                }
            }
        },
        "/auth/forgot_password/confirm_email": {
            "post": {
                "description": "Provide the 6-digit token sent to email",
                "consumes": [
                    "application/vnd.msgpack"
                ],
                "produces": [
                    "application/vnd.msgpack"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Password Reset - Step 2",
                "parameters": [
                    {
                        "description": "6-digit token",
                        "name": "token",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Password Reset session request cookie",
                        "name": "Cookie",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Email confirmed. You're about to reset your password",
                        "schema": {
                            "$ref": "#/definitions/passwordResetService.passReset2RespT"
                        },
                        "headers": {
                            "Set-cookie": {
                                "type": "string",
                                "description": "Password Reset session request cookie"
                            }
                        }
                    },
                    "400": {
                        "description": "Incorrect or expired confirmation token",
                        "schema": {
                            "$ref": "#/definitions/appErrors.HTTPError"
                        },
                        "headers": {
                            "Set-cookie": {
                                "type": "string",
                                "description": "Password Reset session request cookie"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/appErrors.HTTPError"
                        },
                        "headers": {
                            "Set-cookie": {
                                "type": "string",
                                "description": "Password Reset session request cookie"
                            }
                        }
                    }
                }
            }
        },
        "/auth/forgot_password/request_password_reset": {
            "post": {
                "description": "Submit your email to request a password reset",
                "consumes": [
                    "application/vnd.msgpack"
                ],
                "produces": [
                    "application/vnd.msgpack"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Password Reset - Step 1",
                "parameters": [
                    {
                        "description": "Provide your email address",
                        "name": "email",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Proceed to email confirmation",
                        "schema": {
                            "$ref": "#/definitions/passwordResetService.passReset1RespT"
                        },
                        "headers": {
                            "Set-cookie": {
                                "type": "string",
                                "description": "Password Reset session response cookie"
                            }
                        }
                    },
                    "404": {
                        "description": "No user with this email exists",
                        "schema": {
                            "$ref": "#/definitions/appErrors.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/appErrors.HTTPError"
                        }
                    }
                }
            }
        },
        "/auth/forgot_password/reset_password": {
            "post": {
                "description": "Set new password",
                "consumes": [
                    "application/vnd.msgpack"
                ],
                "produces": [
                    "application/vnd.msgpack"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Password Reset user - Step 3",
                "parameters": [
                    {
                        "description": "Choose a new password",
                        "name": "newPassword",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "Conform new password",
                        "name": "confirmNewPassword",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Password Reset session request cookie",
                        "name": "Cookie",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Password changed successfully",
                        "schema": {
                            "$ref": "#/definitions/passwordResetService.passReset3RespT"
                        }
                    },
                    "400": {
                        "description": "Passwords mismatch.",
                        "schema": {
                            "$ref": "#/definitions/appErrors.HTTPError"
                        },
                        "headers": {
                            "Set-cookie": {
                                "type": "string",
                                "description": "Password Reset session response cookie"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/appErrors.HTTPError"
                        },
                        "headers": {
                            "Set-cookie": {
                                "type": "string",
                                "description": "Password Reset session response cookie"
                            }
                        }
                    }
                }
            }
        },
        "/auth/signin": {
            "post": {
                "description": "Signin with email/username and password",
                "consumes": [
                    "application/vnd.msgpack"
                ],
                "produces": [
                    "application/vnd.msgpack"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Signin user",
                "parameters": [
                    {
                        "description": "Email or Username",
                        "name": "EmailOrUsername",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "User Password",
                        "name": "Password",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Signin Success!",
                        "schema": {
                            "$ref": "#/definitions/signinService.signinRespT"
                        },
                        "headers": {
                            "Set-cookie": {
                                "type": "string",
                                "description": "Authenticated user session response cookie containing auth JWT"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/appErrors.HTTPError"
                        }
                    },
                    "404": {
                        "description": "Incorrect credentials",
                        "schema": {
                            "$ref": "#/definitions/appErrors.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/appErrors.HTTPError"
                        }
                    }
                }
            }
        },
        "/auth/signup/register_user": {
            "post": {
                "description": "Provide remaining user credentials",
                "consumes": [
                    "application/vnd.msgpack"
                ],
                "produces": [
                    "application/vnd.msgpack"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Signup user - Step 3",
                "parameters": [
                    {
                        "description": "Choose a username",
                        "name": "username",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "Choose a password",
                        "name": "password",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "User display name",
                        "name": "name",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "User birthday in milliseconds since Unix Epoch",
                        "name": "birthday",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    },
                    {
                        "description": "User bio (optional)",
                        "name": "bio",
                        "in": "body",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Signup session request cookie",
                        "name": "Cookie",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Signup Success",
                        "schema": {
                            "$ref": "#/definitions/signupService.signup3RespT"
                        },
                        "headers": {
                            "Set-cookie": {
                                "type": "string",
                                "description": "Authenticated user session response cookie containing auth JWT"
                            }
                        }
                    },
                    "400": {
                        "description": "Incorrect or expired verification code",
                        "schema": {
                            "$ref": "#/definitions/appErrors.HTTPError"
                        },
                        "headers": {
                            "Set-cookie": {
                                "type": "string",
                                "description": "Signup session response cookie"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/appErrors.HTTPError"
                        },
                        "headers": {
                            "Set-cookie": {
                                "type": "string",
                                "description": "Signup session response cookie"
                            }
                        }
                    }
                }
            }
        },
        "/auth/signup/request_new_account": {
            "post": {
                "description": "Submit email to request a new account",
                "consumes": [
                    "application/vnd.msgpack"
                ],
                "produces": [
                    "application/vnd.msgpack"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Signup user - Step 1",
                "parameters": [
                    {
                        "description": "Provide your email address",
                        "name": "email",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Proceed to email verification",
                        "schema": {
                            "$ref": "#/definitions/signupService.signup1RespT"
                        },
                        "headers": {
                            "Set-cookie": {
                                "type": "string",
                                "description": "Signup session response cookie"
                            }
                        }
                    },
                    "400": {
                        "description": "An account with email already exists",
                        "schema": {
                            "$ref": "#/definitions/appErrors.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/appErrors.HTTPError"
                        }
                    }
                }
            }
        },
        "/auth/signup/verify_email": {
            "post": {
                "description": "Provide the 6-digit code sent to email",
                "consumes": [
                    "application/vnd.msgpack"
                ],
                "produces": [
                    "application/vnd.msgpack"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Signup user - Step 2",
                "parameters": [
                    {
                        "description": "6-digit code",
                        "name": "code",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Signup session request cookie",
                        "name": "Cookie",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Email verified",
                        "schema": {
                            "$ref": "#/definitions/signupService.signup2RespT"
                        },
                        "headers": {
                            "Set-cookie": {
                                "type": "string",
                                "description": "Signup session response cookie"
                            }
                        }
                    },
                    "400": {
                        "description": "Incorrect or expired verification code",
                        "schema": {
                            "$ref": "#/definitions/appErrors.HTTPError"
                        },
                        "headers": {
                            "Set-cookie": {
                                "type": "string",
                                "description": "Signup session response cookie"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/appErrors.HTTPError"
                        },
                        "headers": {
                            "Set-cookie": {
                                "type": "string",
                                "description": "Signup session response cookie"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "UITypes.ClientUser": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "profilePicUrl": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "appErrors.HTTPError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "passwordResetService.passReset1RespT": {
            "type": "object",
            "properties": {
                "msg": {
                    "type": "string"
                }
            }
        },
        "passwordResetService.passReset2RespT": {
            "type": "object",
            "properties": {
                "msg": {
                    "type": "string"
                }
            }
        },
        "passwordResetService.passReset3RespT": {
            "type": "object",
            "properties": {
                "msg": {
                    "type": "string"
                }
            }
        },
        "signinService.signinRespT": {
            "type": "object",
            "properties": {
                "msg": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/UITypes.ClientUser"
                }
            }
        },
        "signupService.signup1RespT": {
            "type": "object",
            "properties": {
                "msg": {
                    "type": "string"
                }
            }
        },
        "signupService.signup2RespT": {
            "type": "object",
            "properties": {
                "msg": {
                    "type": "string"
                }
            }
        },
        "signupService.signup3RespT": {
            "type": "object",
            "properties": {
                "msg": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/UITypes.ClientUser"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "description": "JWT API key in encrypted cookie to protect private endpoints",
            "type": "apiKey",
            "name": "Cookie",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8000",
	BasePath:         "/api",
	Schemes:          []string{"http", "https"},
	Title:            "i9lyfe Backend API",
	Description:      "i9lyfe Social Media Backend API.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
