name: Test, Build, and Deploy

on:
  push:
    branches:
      - main

jobs:
  test-build:
    name: Test and Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: 'npm'

      - name: Clean install dependencies
        run: npm ci

      - name: Setup Postgres with DB
        env:
          PGUSER: ${{ secrets.PGUSER }}
          PGPASSWORD: ${{ secrets.PGPASSWORD }}
          PGDATABASE: ${{ secrets.PGDATABASE }}
        uses: harmon758/postgresql-action@v1
        with:
          postgresql db: $PGDATABASE
          postgresql user: $PGUSER
          postgresql password: $PGPASSWORD

      - name: Start postgresql service
        run: sudo service postgresql start

      - name: Populate DB with test data
        env:
          PGUSER: ${{ secrets.PGUSER }}
          PGHOST: ${{ secrets.PGHOST }}
          PGPASSWORD: ${{ secrets.PGPASSWORD }}
          PGDATABASE: ${{ secrets.PGDATABASE }}
        run: psql -q -f "./${PGDATABASE}_database_backup.sql"
      
      - name: Run tests
        env:
          PGUSER: ${{ secrets.PGUSER }}
          PGHOST: ${{ secrets.PGHOST }}
          PGPASSWORD: ${{ secrets.PGPASSWORD }}
          PGDATABASE: ${{ secrets.PGDATABASE }}
          PGPORT: ${{ secrets.PGPORT }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          MAILING_EMAIL: ${{ secrets.MAILING_EMAIL }}
          MAILING_PASSWORD: ${{ secrets.MAILING_PASSWORD }}
          SIGNUP_SESSION_COOKIE_SECRET: ${{ secrets.SIGNUP_SESSION_COOKIE_SECRET }}
          PASSWORD_RESET_SESSION_COOKIE_SECRET: ${{ secrets.PASSWORD_RESET_SESSION_COOKIE_SECRET }}
          TEST_USER_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}
        run: PGUSER=$PGUSER PGPASSWORD=$PGPASSWORD PGDATABASE=$PGDATABASE PGPORT=$PGPORT JWT_SECRET=$JWT_SECRET MAILING_EMAIL=$MAILING_EMAIL MAILING_PASSWORD=$MAILING_PASSWORD SIGNUP_SESSION_COOKIE_SECRET=$SIGNUP_SESSION_COOKIE_SECRET PASSWORD_RESET_SESSION_COOKIE_SECRET=$PASSWORD_RESET_SESSION_COOKIE_SECRET TEST_USER_PASSWORD=$TEST_USER_PASSWORD npm test
      
      - name: Login to docker
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build docker image
        run: docker build -t thereali9/i9lyfe-server .

      - name: Publish image to docker hub
        run: docker push thereali9/i9lyfe-server:latest